version: '3.3'
services:
  db:
    image: postgres:latest
    container_name: resumeTask
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./new_data_directory:/var/lib/postgresql/data